name: mineral_invite
description: The invite package for the mineral framework
version: 1.0.0

repository: https://github.com/bot-config-dart/MineralInvite
# homepage: https://www.example.com

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=2.17.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0


dependencies:
  mineral_environment: ^1.0.1
  mineral_ioc: ^2.0.0
  mineral_contract: ^1.1.0
  http: ^0.13.3
  udp: ^5.0.3
  mineral:
    path: ../mineral-core

